### PR TITLE
Several improvements, aarch64 support, enable external data checker

### PR DESCRIPTION
**Pull request by xduugu**
There are several changes in this PR and I think it will be easier to review the changes by looking at each commit. The main changes are:
- fetching appdata / metainfo file from upstream
- adding support for aarch64
- enabling external data checker for the sources

### CODE REVIEW

**Comment by xduugu** [comment]
@IsmaelMartinez @jijojosephk
Should I split up this PR so that, for example, the aarch64 support can be merged?

**Comment by IsmaelMartinez** [comment]
I can't check until next week but I think it is small enough to add all changes together. Let's see what @jijojosephk thinks. Thanks a lot for the contributions!

**Comment by xduugu** [comment]
Okay, I will try to keep the PR up-to-date with your releases.

**Comment by IsmaelMartinez** [comment]
@jijojosephk , it might be good if we merge this one soon as it will make it a wee bit easier to manage the versions in flathub. Ta

**Comment by xduugu** [comment]
@IsmaelMartinez @jijojosephk
Updated for v1.4.25 release.

**Pull request merged**
