### PR TITLE
Enable wayland by default

### PR DESCRIPTION
**Pull request by Mikaela**
I have an impression of `--socket=x11` being invalid or automatically removed when `--socket=wayland` is specified and it should be `fallback-x11` to only allow x11 when `wayland` is not being used. The environment variable will start with wayland support enabled when wayland is available and otherwise use X11.

Resolves: #72 

Resolves: IsmaelMartinez/teams-for-linux#1144

### CODE REVIEW

**Comment by jijojosephk** [comment]
We'll consider this PR in the next release. Thank you!

**Comment by Zeitsperre** [comment]
Any updates on this? Would love to see Wayland support here!

**Comment by IsmaelMartinez** [comment]
@Zeitsperre and @Mikaela , can you confirm this works by using `flatpak install --user https://dl.flathub.org/build-repo/145294/com.github.IsmaelMartinez.teams_for_linux.flatpakref` Thanks

**Comment by Zeitsperre** [comment]
@IsmaelMartinez It seems to be rendering with Wayland!

image

**Comment by IsmaelMartinez** [comment]
Are you able to check it all(ISH) works? Like screen sharing and the likes. It is a big user base in flatpak and unfortunately I can't test it. Thanks in advance! Nothing really big testing, just playing with it a bit. I really appreciate it.

**Comment by Zeitsperre** [comment]
@IsmaelMartinez It's been a few days and I haven't noticed any different behaviour from normal (calls, screen sharing, etc.). Seems to be working (for the things I use it for). Thanks again!

**Comment by IsmaelMartinez** [comment]
Thanks! Merging then this. Hopefully it doesn't break for other WM

**Comment by IsmaelMartinez** [comment]
I am suspicious this might have created this issue https://github.com/IsmaelMartinez/teams-for-linux/issues/1487 . It might be unrelated but the issue was just reported after I merged this :/

**Comment by Mikaela** [comment]
Sorry I missed the ping and wouldn't have been able to test since I currently don't have a Teams account due to graduating.

I wouldn't have known about the window resizing, but apparently that was tracked to upstream in the linked issue, https://github.com/electron/electron/issues/44543

**Pull request merged**
