### PR TITLE
Remove unnecessary portal permission

### PR DESCRIPTION
**Pull request by bbhtt**
Fixes https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues/81

### CODE REVIEW

**Comment by jijojosephk** [comment]
Thanks @bbhtt for your contribution  :heart:

**Comment by bbhtt** [comment]
> Thanks @bbhtt for your contribution  :heart: 

The build is held for review by admins because of the permission change. I will approve it later when I'm near the PC.

you don't have to trigger new builds. Also sign up to flathub.org then you'll get emails whenever this happens.

**Comment by jijojosephk** [comment]
Oh, I didn't know that. Looks like some new changes in flathub. Kindly approve whenever you get time. People are eagerly waiting for this release.

**Comment by bbhtt** [comment]
Approved it

**Pull request merged**
